### PR TITLE
Performance Data & SSD fixes

### PR DESCRIPTION
**Pull request by dupondje**
Hi,

I did some fixed to the code to allow 'ON' as default allowed value for disks.
The status is always 'ON' for SSD disks. This is why I also added the MediaType in the output.

Also the Performance Data gave errors because it didn't contain numeric values.
A second bug in it was that some values where just empty.

This is now fixed :)

### CODE REVIEW

**Comment by dangmocrang** [comment]
https://github.com/dangmocrang/check_idrac/pull/24/commits/9344af5d6f6131aa0308bd46b58df87036917b06

For this fix I already concerned before but i chose to add perf even when value not exist, because I use pnp4nagios to store perf and generate graph. If the perf change the number of value it may cause the db of pnp4nagios corrupted unless pnp4nagios was configured to use multiple data files.

**Comment by joke24** [comment]
Hi, can you please merge your script with this fix?

Thank's a lot!

**Comment by dangmocrang** [comment]
Did you remove the "Dont add perf_data if it doesn't contain values" ?

**Comment by dupondje** [comment]
Hi,

Its only the last part of the diff that gives an issue?
You might want to replace the value with 0 if it has no data?

**Comment by dangmocrang** [comment]
i'm sorry, I don't understand your means :(

**Comment by dupondje** [comment]
Hi,

From what I understand the problem is that the order shouldn't change in the performance data?
That can happen with the following change: https://github.com/dangmocrang/check_idrac/pull/24/commits/9344af5d6f6131aa0308bd46b58df87036917b06#diff-ac0a383b76a3b4008abfa60276c9a412L744

For example:
 +                    if hw[3]: perf_list.append('VoltINPUT=%s;;;; ' % hw[3])

If we change it to
 +                    if !hw[3]: hw[3] = 0
 +                    perf_list.append('VoltINPUT=%s;;;; ' % hw[3])

This should be fine?
Then the order will always be correct, except if it has no value, we set it to 0.

**Comment by dangmocrang** [comment]
Ah, yes! Perfect! So did you change the merge request as you describe? If
yes, i will merge the code

On Jul 28, 2016 7:32 PM, "dupondje" <notifications@github.com> wrote:
>
> Hi,
>
> From what I understand the problem is that the order shouldn't change in
the performance data?
> That can happen with the following change:
9344af5#diff-ac0a383b76a3b4008abfa60276c9a412L744
>
> For example:
>
> if hw[3]: perf_list.append('VoltINPUT=%s;;;; ' % hw[3])
>
> If we change it to
>
> if !hw[3]: hw[3] = 0
> perf_list.append('VoltINPUT=%s;;;; ' % hw[3])
>
> This should be fine?
> Then the order will always be correct, except if it has no value, we set
it to 0.

**Comment by dupondje** [comment]
Commited a change to fix this :)

**Pull request merged**
